/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Restaurant;

public class InitialView extends javax.swing.JFrame {

    private Restaurant res = new Restaurant();
    
    public InitialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        CloseButton = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        AppetFire1 = new javax.swing.JButton();
        AppetHire = new javax.swing.JButton();
        MainHire = new javax.swing.JButton();
        MainFire = new javax.swing.JButton();
        DessertHire = new javax.swing.JButton();
        DessertFire = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        WaiterHire = new javax.swing.JButton();
        WaiterFire = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MetroPizza");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(900, 900, 900, 900));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1800, 1000));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel39.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel39.setText("Current Status:");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(1130, 760, 340, 30);

        TimeLabel.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        TimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        TimeLabel.setText("TIME TO CLOSE:");
        getContentPane().add(TimeLabel);
        TimeLabel.setBounds(80, 80, 370, 60);

        CloseButton.setBackground(new java.awt.Color(197, 50, 79));
        CloseButton.setForeground(new java.awt.Color(255, 255, 255));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ExitIcon.png"))); // NOI18N
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton);
        CloseButton.setBounds(1720, 10, 60, 50);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 0, 1190, 280);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 90, 0, 0);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -10, 1720, 300);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PizzaIcon.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 540, 300, 230);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1310, -10, 1720, 300);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AppetizerIcon.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 360, 170, 160);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DessertIcon.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 790, 160, 170);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ManagerIcon.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(990, 720, 130, 160);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WaiterIcon.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1000, 380, 160, 210);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WaiterChiefIcon.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1400, 690, 180, 240);

        jLabel12.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel12.setText("Number of Main Dishes Available:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 660, 360, 30);

        jLabel25.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel25.setText("Number of Appetizer Cooks:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(240, 400, 340, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(230, 760, 628, 10);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(230, 540, 630, 10);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(910, 600, 10, 420);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(910, 240, 10, 420);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(910, 470, 10, 420);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 540, 630, 10);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 760, 628, 10);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1360, 700, 10, 210);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1150, 650, 650, 10);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RedWineBackground.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(980, 650, 628, 10);

        AppetFire1.setBackground(new java.awt.Color(255, 204, 0));
        AppetFire1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        AppetFire1.setForeground(new java.awt.Color(255, 255, 255));
        AppetFire1.setText("FIRE");
        AppetFire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppetFire1ActionPerformed(evt);
            }
        });
        getContentPane().add(AppetFire1);
        AppetFire1.setBounds(670, 440, 150, 40);

        AppetHire.setBackground(new java.awt.Color(255, 204, 0));
        AppetHire.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        AppetHire.setForeground(new java.awt.Color(255, 255, 255));
        AppetHire.setText("HIRE");
        AppetHire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppetHireActionPerformed(evt);
            }
        });
        getContentPane().add(AppetHire);
        AppetHire.setBounds(670, 370, 150, 40);

        MainHire.setBackground(new java.awt.Color(255, 204, 0));
        MainHire.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        MainHire.setForeground(new java.awt.Color(255, 255, 255));
        MainHire.setText("HIRE");
        MainHire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainHireActionPerformed(evt);
            }
        });
        getContentPane().add(MainHire);
        MainHire.setBounds(670, 590, 150, 40);

        MainFire.setBackground(new java.awt.Color(255, 204, 0));
        MainFire.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        MainFire.setForeground(new java.awt.Color(255, 255, 255));
        MainFire.setText("FIRE");
        MainFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainFireActionPerformed(evt);
            }
        });
        getContentPane().add(MainFire);
        MainFire.setBounds(670, 660, 150, 40);

        DessertHire.setBackground(new java.awt.Color(255, 204, 0));
        DessertHire.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        DessertHire.setForeground(new java.awt.Color(255, 255, 255));
        DessertHire.setText("HIRE");
        DessertHire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertHireActionPerformed(evt);
            }
        });
        getContentPane().add(DessertHire);
        DessertHire.setBounds(670, 820, 150, 40);

        DessertFire.setBackground(new java.awt.Color(255, 204, 0));
        DessertFire.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        DessertFire.setForeground(new java.awt.Color(255, 255, 255));
        DessertFire.setText("FIRE");
        DessertFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DessertFireActionPerformed(evt);
            }
        });
        getContentPane().add(DessertFire);
        DessertFire.setBounds(670, 890, 150, 40);

        jLabel23.setText("jLabel23");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(200, 120, 48, 16);

        jLabel31.setFont(new java.awt.Font("Candara", 1, 60)); // NOI18N
        jLabel31.setText("WAITERS");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(1280, 300, 270, 60);

        jLabel26.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel26.setText("CHIEF WAITER");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(1510, 700, 240, 50);

        jLabel32.setFont(new java.awt.Font("Candara", 1, 36)); // NOI18N
        jLabel32.setText("MANAGER");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(1130, 700, 190, 50);

        jLabel30.setFont(new java.awt.Font("Candara", 1, 60)); // NOI18N
        jLabel30.setText("COOKS");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(120, 100, 270, 60);

        jLabel29.setFont(new java.awt.Font("Candara", 1, 60)); // NOI18N
        jLabel29.setText("COOKS");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(340, 300, 270, 60);

        jLabel27.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel27.setText("Number of Main Cooks:");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(240, 620, 340, 30);

        jLabel33.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel33.setText("Number of Appetizers Available:");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(240, 440, 340, 30);

        jLabel34.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel34.setText("Number of Dessert Cooks:");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(240, 840, 340, 30);

        jLabel35.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel35.setText("Number of Desserts Available:");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(240, 880, 360, 30);

        jLabel36.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel36.setText("Current Status:");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(1540, 760, 340, 30);

        jLabel37.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel37.setText("Number of Orders:");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(1190, 490, 340, 30);

        WaiterHire.setBackground(new java.awt.Color(255, 204, 0));
        WaiterHire.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        WaiterHire.setForeground(new java.awt.Color(255, 255, 255));
        WaiterHire.setText("HIRE");
        WaiterHire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterHireActionPerformed(evt);
            }
        });
        getContentPane().add(WaiterHire);
        WaiterHire.setBounds(1600, 430, 150, 40);

        WaiterFire.setBackground(new java.awt.Color(255, 204, 0));
        WaiterFire.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        WaiterFire.setForeground(new java.awt.Color(255, 255, 255));
        WaiterFire.setText("FIRE");
        WaiterFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterFireActionPerformed(evt);
            }
        });
        getContentPane().add(WaiterFire);
        WaiterFire.setBounds(1600, 500, 150, 40);

        jLabel38.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel38.setText("Number of Waiters:");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(1190, 450, 340, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhiteBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(0, 280, 1910, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AppetFire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppetFire1ActionPerformed
        
        this.res.fireACook(1);
        
    }//GEN-LAST:event_AppetFire1ActionPerformed

    private void AppetHireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppetHireActionPerformed
      this.res.hireACook(1);
    }//GEN-LAST:event_AppetHireActionPerformed

    private void MainHireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainHireActionPerformed
        this.res.hireMCook(1);
    }//GEN-LAST:event_MainHireActionPerformed

    private void MainFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainFireActionPerformed
       this.res.fireMCook(1);
    }//GEN-LAST:event_MainFireActionPerformed

    private void DessertHireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertHireActionPerformed
       this.res.hireDCook(1);
    }//GEN-LAST:event_DessertHireActionPerformed

    private void DessertFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DessertFireActionPerformed
       this.res.fireDCook(1);
    }//GEN-LAST:event_DessertFireActionPerformed

    private void WaiterHireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterHireActionPerformed
       this.res.hireWaiter(1);
    }//GEN-LAST:event_WaiterHireActionPerformed

    private void WaiterFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterFireActionPerformed
       this.res.fireWaiter(1);
    }//GEN-LAST:event_WaiterFireActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
       
        int n=0;
        System.exit(n);
        
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialView().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppetFire1;
    private javax.swing.JButton AppetHire;
    private javax.swing.JToggleButton CloseButton;
    private javax.swing.JButton DessertFire;
    private javax.swing.JButton DessertHire;
    private javax.swing.JButton MainFire;
    private javax.swing.JButton MainHire;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton WaiterFire;
    private javax.swing.JButton WaiterHire;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
